export const SEED_MOVIE_TITLES = [
  'Clue',
  'Rocky Horror Picture Show',
  'Interview with a Vampire',
  'Knives Out',
  'Jurassic Park',
  'Cha Cha Real Smooth',
  'Blade Runner 2049',
  'Oppenheimer',
  'Barbie',
  'Coraline',
  'Shawshank Redemption',
  'Memento',
  'The Truman Show',
  'The Martian',
  'The Secret Life of Walter Mitty',
  'Goodfellas',
  'Something Wicked This Way Comes',
  'True Grit',
  'The Holdovers',
  'Grand Budapest Hotel',
  'Fantastic Mr Fox',
  'Men',
  'DnD movie',
  'Apocalypse Now',
  'Misery',
  'Chronicle',
  'World War Z',
  'Kung Fu Panda 2',
  'Howls Moving Castle',
  'Grave of the Fireflies',
  'Princess Mononoke',
  'Arrietty',
  'A Quiet Place',
  'Moonrise Kingdom',
  'The Killer',
  'All Quiet on the Western Front',
  'The Godfather',
  'The Mask',
  'Puss in Boots: the Last Wish',
  'Austin Powers',
  'Fried Green Tomatoes',
  'Poppy',
  'Hoodwinked',
  'Empire Records',
  'Scott pilgrim against the world',
  'The lobster',
  'Peter Pan (live)',
  'Hacksaw Ridge',
  'Mrs Doubtfire',
  'Juno',
  'Working girl',
  'Dead poets society',
  '3 Billboards Outside Ebbing Missouri',
  'Princess Bride',
  'Willow',
  'Who framed roger rabbit',
  'Ever after',
  'Flubber',
  'Civil War',
  'The thief and the cobbler',
  'Saving Private Ryan',
  'The Lighthouse',
  'Pans Labyrinth',
  'Indian horse',
  'The ritual',
  'Train to Busan',
  'Bullet Train',
  'Spirited away',
  'Kill Bill',
  '12 Angry Men',
  'Hundreds of Beavers',
  'Jerry Maguire',
  'Zodiac',
  'The Sandlot',
  'School of Rock',
  'Lincoln',
  'Wake up Dead Man',
  'Jaws',
  'Invictus',
  'The importance of being Earnest',
  "Ferris Bueller's Day Off",
  'The Green Mile',
  'The Green Book',
  'The Pianist',
  'District 9',
  'The Man From U.N.C.L.E.',
];

export function createSeedData() {
  const seen = new Set();
  const movies = [];

  for (const title of SEED_MOVIE_TITLES) {
    const key = title.trim().toLowerCase();
    if (!key || seen.has(key)) continue;
    seen.add(key);
    movies.push({
      id: crypto.randomUUID(),
      title: title.trim(),
      ratings: {},
    });
  }

  return {
    movies,
    people: [],
    updatedAt: new Date().toISOString(),
  };
}
